name: flutter_rider_app
description: "Hamar Bazar Delivery Rider Live Location Tracking App (Background Location & Render Sync)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  battery_plus: ^5.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
